### ISSUE TITLE
Improving Ingredients Regex

### ISSUE THREAD

**Issue by brianzhan** [BrianMargolis/RecipeTransformer#9]
Current accuracy isn't that great

**Comment by MengWu2018** [comment]
right now, we'd parse teh following
Name: 
	Quantity: 12 lasagna
	Descriptors: 
	Preparations: 	Category: vegetable

But the ingredient name is actually 12 lasagna noodles. Inability to recognize this.

In the same link, we get "Name: 
	Quantity: 1 egg
	Descriptors: 
	Preparations: 	Category: vegetable" but result should actually just be 1 egg.

We should basically be excluding any "ingredient names" like "egg and lasagna noodles" if it comes after a number which seems to be the issue. Use this link as reference for the source of error. We were running main.py

https://www.allrecipes.com/recipe/23600/worlds-best-lasagna/?clickId=right%20rail1&internalSource=rr_feed_recipe_sb&referringId=73634%20referringContentType%3Drecipe

**Comment by BrianMargolis** [comment]
Not sure how this can be done, we'd have to somehow recognize that "lasagna" or "egg" is an ingredient. Unless we start using lots and lots of keywords for ingredients, this probably isn't fixable.
